version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.23.7
    ports:
      - "8080:8080"  # REST API
      - "50051:50051"  # gRPC API
    restart: on-failure:0
    env_file:
      - backend/.env
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      OPENAI_ORGANIZATION: ''
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - weaviate_network

volumes:
  weaviate_data:

networks:
  weaviate_network:
    driver: bridge 